apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
patches:
- patch: |-
    - op: replace
      path: /metadata/namespace
      value: aws-local-runtime
  target:
    group: apps
    kind: Deployment
    version: v1
- patch: |-
    - op: replace
      path: /metadata/namespace
      value: aws-local-runtime
  target:
    kind: ServiceAccount
    version: v1
- patch: |-
    - op: replace
      path: /subjects/0/namespace
      value: aws-local-runtime
  target:
    group: rbac.authorization.k8s.io
    kind: ClusterRoleBinding
    version: v1
- patch: |-
    - op: replace
      path: /data/host
      value: "http://argocd-server.aws-local-runtime.svc.cluster.local"
  target:
    kind: ConfigMap
    version: v1
- patch: |-
    - op: replace
      path: /data/integration
      value: argocd-aws-local-runtime
  target:
    kind: ConfigMap
    version: v1
resources:
- github.com/codefresh-io/cli-v2/manifests/argo-agent?ref=v0.0.232
