apiVersion: kustomize.config.k8s.io/v1beta1
configMapGenerator:
- behavior: merge
  literals:
  - argoWorkflowsInsecure=true
  - cfHost=http://philipp-platform.ngrok.io
  - cors=http://philipp-platform.ngrok.io,http://local.codefresh.io
  - env=production
  - graphqlPlayground=tru
  name: cap-app-proxy-cm
kind: Kustomization
namespace: aws-local-runtime
resources:
- ../../base
- ingress.yaml
