apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: codefresh-runtime-applications
  labels:
    codefresh.io/entity: git-source
    codefresh.io/internal: 'false'
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: git-sources
  source:
    repoURL: https://github.com/PhilippPlotnikov/codefresh-runtime-applications.git
    path: .
    targetRevision: HEAD
    directory:
      include: '*'
      exclude: ''
      recurse: true
  destination:
    namespace: codefresh-hosted
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true
